json.extract!(
  project,
        :id,
        :author_id,
        :group,
        :name,
        :description,
        :url,
        :flagged,
        :flag,
        :tasks,
        :slack_id,
        :calendar_id,
        :tags,
        :youtube_link,
        :inspiration_links,
        :involvement_level
)
