json.extract!(
  project,
        :id,
        :author_id,
        :dev_id,
        :name,
        :pitch,
        :description,
        :url,
        :view_count,
        :expiration_date,
        :flagged,
        :flag
)
