json.extract!(
  project,
        :id,
        :author_id,
        :group,
        :name,
        :description,
        :url,
        :view_count,
        :expiration_date,
        :flagged,
        :flag,
        :tasks,
        :slack_id,
        :calendar_id
)
