module.exports = {
  SESSION_RECEIVED: "SESSION_RECEIVED",
  USER_RECEIVED: "USER_RECEIVED",
  SESSION_DESTROYED: "SESSION_DESTROYED",
  INVALID_ENTRY: "INVALID_ENTRY",
  PROJECT_RECEIVED: "PROJECT_RECEIVED",
  UPDATED_PROJECT_RECEIVED: "UPDATED_PROJECT_RECEIVED",
  FLAG_RECEIVED: "FLAG_RECEIVED",
  COHORT_RECEIVED: "COHORT_RECEIVED",
  GROUP_RECEIVED: "GROUP_RECEIVED"
}
