module.exports = {
  SESSION_RECIEVED: "SESSION_RECIEVED",
  USER_RECIEVED: "USER_RECIEVED",
  SESSION_DESTROYED: "SESSION_DESTROYED",
  INVALID_ENTRY: "INVALID_ENTRY",
  PROJECT_RECIEVED: "PROJECT_RECIEVED",
  FLAG_RECIEVED: "FLAG_RECIEVED",
  COHORT_RECIEVED: "COHORT_RECIEVED",
  GROUP_RECIEVED: "GROUP_RECIEVED"
}
